In [1]:
import pandas

/home/pivarski/.local/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/pivarski/.local/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/pivarski/.local/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/pivarski/.local/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/pivarski/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: Ru

In [2]:
import os
os.chdir(os.path.expanduser("~"))

import pandas
import numpy
from awkward import JaggedArray, Table

In [3]:
a = JaggedArray.fromiter([[0.0, 1.1, 2.2], [], [3.3, 4.4], [5.5, 6.6, 7.7, 8.8, 9.9]])
a

<JaggedArray [[0.  1.1 2.2] [] [3.3 4.4] [5.5 6.6 7.7 8.8 9.9]] at 73810a378590>

In [4]:
print(a.starts)
print(a.stops)
print(a.content)

[0 3 3 5]
[ 3  3  5 10]
[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]


In [5]:
a + 100

<JaggedArray [[100.  101.1 102.2] [] [103.3 104.4] [105.5 106.6 107.7 108.8 109.9]] at 738131f99890>

In [6]:
a + numpy.array([100, 200, 300, 400])

<JaggedArray [[100.  101.1 102.2] [] [303.3 304.4] [405.5 406.6 407.7 408.8 409.9]] at 73810a378790>

In [7]:
a + numpy.array([100, 200, 300, 400, 500])

ValueError: cannot broadcast JaggedArray of shape (4,) with Numpy array of shape (5,)

In [ ]:
a[::2]

In [ ]:
a[::2, 1]

In [8]:
b = JaggedArray.fromoffsets([0, 2, 4], a)
b

<JaggedArray [[[0.  1.1 2.2] []] [[3.3 4.4] [5.5 6.6 7.7 8.8 9.9]]] at 73810a297090>

In [9]:
b[1, :, 1]

array([4.4, 6.6])

In [10]:
a.tolist()

[[0.0, 1.1, 2.2], [], [3.3, 4.4], [5.5, 6.6, 7.7, 8.8, 9.9]]

In [11]:
b.tolist()

[[[0.0, 1.1, 2.2], []], [[3.3, 4.4], [5.5, 6.6, 7.7, 8.8, 9.9]]]

In [12]:
a.pandas()

0
0 0  0.0
  1  1.1
  2  2.2
2 0  3.3
  1  4.4
3 0  5.5
  1  6.6
  2  7.7
  3  8.8
  4  9.9

In [13]:
b.pandas()

0
0 0 0  0.0
    1  1.1
    2  2.2
1 0 0  3.3
    1  4.4
  1 0  5.5
    1  6.6
    2  7.7
    3  8.8
    4  9.9

In [20]:
a.parents

array([0, 0, 0, 2, 2, 3, 3, 3, 3, 3])

In [21]:
a.index

<JaggedArray [[0 1 2] [] [0 1] [0 1 2 3 4]] at 73810a2d9f50>

In [14]:
print(a.type)
print(b.type)

[0, 4) -> [0, inf) -> float64
[0, 2) -> [0, inf) -> [0, inf) -> float64


In [15]:
a.sum()

array([ 3.3,  0. ,  7.7, 38.5])

In [16]:
a.max()

array([ 2.2, -inf,  4.4,  9.9])

In [17]:
a.argmax()

<JaggedArray [[2] [] [1] [4]] at 73810a213f10>

In [18]:
a[a.argmax()]

<JaggedArray [[2.2] [] [4.4] [9.9]] at 73810a297890>