In [1]:
import pandas

/home/pivarski/.local/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/pivarski/.local/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/pivarski/.local/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/pivarski/.local/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/pivarski/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: Ru

In [2]:
import os
os.chdir(os.path.expanduser("~"))

import pandas
import numpy
from awkward import JaggedArray, Table

In [3]:
a = JaggedArray.fromiter([[0.0, 1.1, 2.2], [], [3.3, 4.4], [5.5, 6.6, 7.7, 8.8, 9.9]])
a

<JaggedArray [[0.  1.1 2.2] [] [3.3 4.4] [5.5 6.6 7.7 8.8 9.9]] at 7d45afc8b710>

In [4]:
print(a.starts)
print(a.stops)
print(a.content)

[0 3 3 5]
[ 3  3  5 10]
[0.  1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]


In [5]:
a + 100

<JaggedArray [[100.  101.1 102.2] [] [103.3 104.4] [105.5 106.6 107.7 108.8 109.9]] at 7d45df522f10>

In [6]:
a + numpy.array([100, 200, 300, 400])

<JaggedArray [[100.  101.1 102.2] [] [303.3 304.4] [405.5 406.6 407.7 408.8 409.9]] at 7d45afee5f50>

In [7]:
a + numpy.array([100, 200, 300, 400, 500])

ValueError: cannot broadcast JaggedArray of shape (4,) with Numpy array of shape (5,)

In [ ]:
a[::2]

In [ ]:
a[::2, 1]

In [ ]:
b = JaggedArray.fromoffsets([0, 2, 4], a)
b

In [8]:
b[1, :, 1]

NameError: name 'b' is not defined

In [9]:
a.tolist()

[[0.0, 1.1, 2.2], [], [3.3, 4.4], [5.5, 6.6, 7.7, 8.8, 9.9]]

In [10]:
b.tolist()

NameError: name 'b' is not defined

In [11]:
a.pandas()

0
0 0  0.0
  1  1.1
  2  2.2
2 0  3.3
  1  4.4
3 0  5.5
  1  6.6
  2  7.7
  3  8.8
  4  9.9

In [12]:
b.pandas()

NameError: name 'b' is not defined

In [ ]:
a.parents

In [13]:
a.index

<JaggedArray [[0 1 2] [] [0 1] [0 1 2 3 4]] at 7d45afb394d0>

In [14]:
print(a.type)
print(b.type)

[0, 4) -> [0, inf) -> float64


NameError: name 'b' is not defined

In [15]:
a.sum()

array([ 3.3,  0. ,  7.7, 38.5])

In [16]:
a.max()

array([ 2.2, -inf,  4.4,  9.9])

In [17]:
a.argmax()

<JaggedArray [[2] [] [1] [4]] at 7d45afb39bd0>

In [18]:
a[a.argmax()]

<JaggedArray [[2.2] [] [4.4] [9.9]] at 7d45afa00dd0>

In [19]:
a[a.argmax()].flatten()

array([2.2, 4.4, 9.9])

In [20]:
a > 5

<JaggedArray [[False False False] [] [False False] [ True  True  True  True  True]] at 7d45afb39c90>

In [21]:
a[a > 5]

<JaggedArray [[] [] [] [5.5 6.6 7.7 8.8 9.9]] at 7d45afb39ed0>

In [22]:
a[a > 5].sum()

array([ 0. ,  0. ,  0. , 38.5])

In [25]:
c = Table.zip(one=[0, 1, 2, 3, 4], two=[0.0, 1.1, 2.2, 3.3, 4.4])
c.pandas()

two  one
0  0.0    0
1  1.1    1
2  2.2    2
3  3.3    3
4  4.4    4

In [26]:
d = Table.fromrec(numpy.array([(0, 0.0), (1, 1.1), (2, 2.2), (3, 3.3), (4, 4.4)], dtype=[("one", int), ("two", float)]))
d.pandas()

one  two
0    0  0.0
1    1  1.1
2    2  2.2
3    3  3.3
4    4  4.4

In [27]:
c["two"], d["two"]

(array([0. , 1.1, 2.2, 3.3, 4.4]), array([0. , 1.1, 2.2, 3.3, 4.4]))

In [28]:
c[2], d[2]

(<Table.Row 2>, <Table.Row 2>)

In [29]:
c[2].tolist(), d[2].tolist()

AttributeError: 'tolist'

In [24]:
# cross